/* eslint-disable @typescript-eslint/no-explicit-any */
// lib/utils/handover.ts
// Generates downloadable handover ZIP package

import { prisma } from '@/lib/db/prisma'
import archiver from 'archiver'
import { PassThrough } from 'stream'

export async function generateHandoverPackage(projectId: string): Promise<Buffer> {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      handover: true,
      documents: {
        where: {
          type: { in: ['AGREEMENT', 'INVOICE', 'HANDOVER'] },
        },
        include: { attachments: true },
      },
      tasks: {
        where: { status: 'DONE' },
        select: { title: true, phase: true, completedAt: true },
      },
      milestones: {
        where: { isCompleted: true },
        select: { title: true, completedAt: true },
      },
      clientProfile: {
        include: { user: { select: { name: true, email: true } } },
      },
      projectManager: { select: { name: true, email: true } },
    },
  })

  if (!project) throw new Error('Project not found')

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    const passThrough = new PassThrough()
    const archive = archiver('zip', { zlib: { level: 9 } })

    passThrough.on('data', (chunk) => chunks.push(chunk))
    passThrough.on('end', () => resolve(Buffer.concat(chunks)))
    passThrough.on('error', reject)
    archive.on('error', reject)
    archive.pipe(passThrough)

    // README
    const readme = generateReadme(project)
    archive.append(readme, { name: 'README.md' })

    // Project Summary
    const summary = generateProjectSummary(project)
    archive.append(summary, { name: 'project-summary.md' })

    // Credentials (if any)
    if (project.handover?.credentialsNotes) {
      const credentials = `# Credentials & Access Details\n\n${project.handover.credentialsNotes}\n\n⚠️  Keep this file secure. Delete after storing credentials in a password manager.\n`
      archive.append(credentials, { name: 'credentials/CREDENTIALS.md' })
    }

    // Deployment Info
    if (project.handover) {
      const deployment = generateDeploymentDoc(project.handover)
      archive.append(deployment, { name: 'deployment/DEPLOYMENT.md' })
    }

    // Task completion log
    const taskLog = generateTaskLog(project.tasks)
    archive.append(taskLog, { name: 'delivery/TASK_LOG.md' })

    // Milestone log
    const milestoneLog = generateMilestoneLog(project.milestones)
    archive.append(milestoneLog, { name: 'delivery/MILESTONES.md' })

    archive.finalize()
  })
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateReadme(project: any): string {
  return `# ${project.name} — Handover Package

**Project Type:** ${project.type.replace(/_/g, ' ')}
**Delivered by:** Formium Alliance LLP
**Handover Date:** ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
**Client:** ${project.clientProfile?.user?.name || 'N/A'}
**Project Manager:** ${project.projectManager?.name || 'N/A'}

---

## Contents

- \`README.md\` — This file
- \`project-summary.md\` — Full project overview
- \`credentials/\` — Access credentials and API keys
- \`deployment/\` — Deployment and hosting instructions
- \`delivery/\` — Task and milestone completion records
- \`documents/\` — Agreements, invoices, and signed documents
- \`assets/\` — Brand assets and design files

---

## Getting Support

For any questions about this project, contact Formium Alliance at:
- Email: projects@formiumalliance.com
- Website: https://formiumalliance.com

---

*This handover package was generated by Formium Projects.*
`
}

function generateProjectSummary(project: any): string {
  return `# Project Summary

## ${project.name}

**Description:** ${project.description || 'N/A'}
**Type:** ${project.type.replace(/_/g, ' ')}
**Status:** ${project.status}
**Progress:** ${project.progress}%

## Timeline

- **Start Date:** ${project.startDate ? new Date(project.startDate).toLocaleDateString('en-IN') : 'N/A'}
- **Expected End:** ${project.expectedEndDate ? new Date(project.expectedEndDate).toLocaleDateString('en-IN') : 'N/A'}
- **Actual End:** ${project.actualEndDate ? new Date(project.actualEndDate).toLocaleDateString('en-IN') : 'N/A'}

## Financial

- **Agreed Budget:** ${project.currency} ${project.agreedBudget?.toLocaleString('en-IN') || 'N/A'}
- **Advance Paid:** ${project.currency} ${project.advanceAmount?.toLocaleString('en-IN') || 'N/A'}

## Team

- **Project Manager:** ${project.projectManager?.name || 'N/A'} (${project.projectManager?.email || ''})

## Live URLs

${project.handover?.liveUrl ? `- **Live:** ${project.handover.liveUrl}` : ''}
${project.handover?.stagingUrl ? `- **Staging:** ${project.handover.stagingUrl}` : ''}
${project.handover?.repositoryUrl ? `- **Repository:** ${project.handover.repositoryUrl}` : ''}
`
}

function generateDeploymentDoc(handover: any): string {
  return `# Deployment & Hosting Guide

## Live Environment

- **Live URL:** ${handover.liveUrl || 'N/A'}
- **Staging URL:** ${handover.stagingUrl || 'N/A'}
- **Repository:** ${handover.repositoryUrl || 'N/A'}
- **Platform:** ${handover.deploymentPlatform || 'N/A'}

## Deployment Notes

${handover.deploymentNotes || 'No deployment notes provided.'}

## Maintenance Notes

${handover.maintenanceNotes || 'No maintenance notes provided.'}

---

*Contact Formium Alliance for deployment support.*
`
}

function generateTaskLog(tasks: any[]): string {
  const byPhase = tasks.reduce((acc: any, task: any) => {
    if (!acc[task.phase]) acc[task.phase] = []
    acc[task.phase].push(task)
    return acc
  }, {})

  let log = `# Task Completion Log\n\nTotal tasks completed: ${tasks.length}\n\n`
  
  for (const [phase, phaseTasks] of Object.entries(byPhase)) {
    log += `## ${phase.replace(/_/g, ' ')}\n\n`
    for (const task of (phaseTasks as Array<{ title: string; phase: string; completedAt?: Date | null }>)) {
      log += `- [x] ${task.title}${task.completedAt ? ` _(${new Date(task.completedAt).toLocaleDateString('en-IN')})_` : ''}\n`
    }
    log += '\n'
  }

  return log
}

function generateMilestoneLog(milestones: any[]): string {
  let log = `# Milestones Achieved\n\n`
  for (const ms of milestones) {
    log += `- **${ms.title}** — ${ms.completedAt ? new Date(ms.completedAt).toLocaleDateString('en-IN') : 'Completed'}\n`
  }
  return log
}
